name: Deployment

env:
  TF_WORKSPACE: ${{ vars.TF_WORKSPACE }}

on:
  push:
    branches: ['**']

jobs:
  caller-deployment:
    uses: ./.github/workflows/environments.yml
    with:
      environments: "['dev', 'qa']"