name: Deployment

env:
  TF_WORKSPACE: ${{ vars.TF_WORKSPACE }}
  infra_envs: [dev, qa, stg, prod]

on:
  push:
    branches:
      - '**'

jobs:
  deployment:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        environment: ${{ env.infra_envs }}
    environment: ${{ matrix.environment }}
    steps:
      - name: deploy
        run: sleep 35 && echo "$TF_WORKSPACE"