name: Deployment

env:
  TF_WORKSPACE: ${{ vars.TF_WORKSPACE }}

on: 
  workflow_call:
    inputs:
      environments:
        required: true

jobs:
  deployment:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        environment: ${{ inputs.environments }}
        # environment: [dev]
        # environment: [dev, qa, prod]
        # exclude:
        #   - environment: dev
        #   - environment: qa
    environment: ${{ matrix.environment }}
    # if: ${{ github.ref_name == 'develop' && matrix.environment == 'dev' }}
    steps:
      - name: deploy
        if: ${{ github.ref_name == 'develop' && matrix.environment == 'dev' }}
        run: sleep 15 && echo "$TF_WORKSPACE"